const pokemonKanto = [
  {
    number: 1,
    name: "Bulbasaur",
    type: ["Grass", "Poison"],
    game: "",
    dlc: false,
    location: "",
    area: "",
    habitat: "",
    obtainMethod: "",
    requirements: "",
    evolvesFrom: "",
    evolvesInto: "Ivysaur",
    evolutionMethod: "",
    tip: ""
  },
  {
    number: 2,
    name: "Ivysaur",
    type: ["Grass", "Poison"],
    game: "",
    dlc: false,
    location: "",
    area: "",
    habitat: "",
    obtainMethod: "",
    requirements: "",
    evolvesFrom: "Bulbasaur",
    evolvesInto: "Venusaur",
    evolutionMethod: "",
    tip: ""
  },
  {
    number: 3,
    name: "Venusaur",
    type: ["Grass", "Poison"],
    game: "",
    dlc: false,
    location: "",
    area: "",
    habitat: "",
    obtainMethod: "",
    requirements: "",
    evolvesFrom: "Ivysaur",
    evolvesInto: "",
    evolutionMethod: "",
    tip: ""
  },
  {
    number: 4,
    name: "Charmander",
    type: ["Fire"],
    game: "",
    dlc: false,
    location: "",
    area: "",
    habitat: "",
    obtainMethod: "",
    requirements: "",
    evolvesFrom: "",
    evolvesInto: "Charmeleon",
    evolutionMethod: "",
    tip: ""
  },
  {
    number: 5,
    name: "Charmeleon",
    type: ["Fire"],
    game: "",
    dlc: false,
    location: "",
    area: "",
    habitat: "",
    obtainMethod: "",
    requirements: "",
    evolvesFrom: "Charmander",
    evolvesInto: "Charizard",
    evolutionMethod: "",
    tip: ""
  },
  {
    number: 6,
    name: "Charizard",
    type: ["Fire", "Flying"],
    game: "",
    dlc: false,
    location: "",
    area: "",
    habitat: "",
    obtainMethod: "",
    requirements: "",
    evolvesFrom: "Charmeleon",
    evolvesInto: "",
    evolutionMethod: "",
    tip: ""
  },
  {
    number: 7,
    name: "Squirtle",
    type: ["Water"],
    game: "",
    dlc: false,
    location: "",
    area: "",
    habitat: "",
    obtainMethod: "",
    requirements: "",
    evolvesFrom: "",
    evolvesInto: "Wartortle",
    evolutionMethod: "",
    tip: ""
  },
  {
    number: 8,
    name: "Wartortle",
    type: ["Water"],
    game: "",
    dlc: false,
    location: "",
    area: "",
    habitat: "",
    obtainMethod: "",
    requirements: "",
    evolvesFrom: "Squirtle",
    evolvesInto: "Blastoise",
    evolutionMethod: "",
    tip: ""
  },
  {
    number: 9,
    name: "Blastoise",
    type: ["Water"],
    game: "",
    dlc: false,
    location: "",
    area: "",
    habitat: "",
    obtainMethod: "",
    requirements: "",
    evolvesFrom: "Wartortle",
    evolvesInto: "",
    evolutionMethod: "",
    tip: ""
  },
  {
    number: 10,
    name: "Caterpie",
    type: ["Bug"],
    game: "",
    dlc: false,
    location: "",
    area: "",
    habitat: "",
    obtainMethod: "",
    requirements: "",
    evolvesFrom: "",
    evolvesInto: "Metapod",
    evolutionMethod: "",
    tip: ""
  }
,
{
  number: 11,
  name: "Metapod",
  type: ["Bug"],
  game: "",
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "Caterpie",
  evolvesInto: "Butterfree",
  evolutionMethod: "",
  tip: ""
},
{
  number: 12,
  name: "Butterfree",
  type: ["Bug", "Flying"],
  game: "",
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "Metapod",
  evolvesInto: "",
  evolutionMethod: "",
  tip: ""
},
{
  number: 13,
  name: "Weedle",
  type: ["Bug", "Poison"],
  game: "",
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "",
  evolvesInto: "Kakuna",
  evolutionMethod: "",
  tip: ""
},
{
  number: 14,
  name: "Kakuna",
  type: ["Bug", "Poison"],
  game: "",
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "Weedle",
  evolvesInto: "Beedrill",
  evolutionMethod: "",
  tip: ""
},
{
  number: 15,
  name: "Beedrill",
  type: ["Bug", "Poison"],
  game: "",
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "Kakuna",
  evolvesInto: "",
  evolutionMethod: "",
  tip: ""
},
{
  number: 16,
  name: "Pidgey",
  type: ["Normal", "Flying"],
  game: "",
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "",
  evolvesInto: "Pidgeotto",
  evolutionMethod: "",
  tip: ""
},
{
  number: 17,
  name: "Pidgeotto",
  type: ["Normal", "Flying"],
  game: "",
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "Pidgey",
  evolvesInto: "Pidgeot",
  evolutionMethod: "",
  tip: ""
},
{
  number: 18,
  name: "Pidgeot",
  type: ["Normal", "Flying"],
  game: "",
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "Pidgeotto",
  evolvesInto: "",
  evolutionMethod: "",
  tip: ""
},
{
  number: 19,
  name: "Rattata",
  type: ["Normal"],
  game: "",
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "",
  evolvesInto: "Raticate",
  evolutionMethod: "",
  tip: ""
},
{
  number: 20,
  name: "Raticate",
  type: ["Normal"],
  game: "",
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "Rattata",
  evolvesInto: "",
  evolutionMethod: "",
  tip: ""
},
{
  number: 21,
  name: "Spearow",
  type: ["Normal", "Flying"],
  game: "",
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "",
  evolvesInto: "Fearow",
  evolutionMethod: "",
  tip: ""
},
{
  number: 22,
  name: "Fearow",
  type: ["Normal", "Flying"],
  game: "",
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "Spearow",
  evolvesInto: "",
  evolutionMethod: "",
  tip: ""
},
{
  number: 23,
  name: "Ekans",
  type: ["Poison"],
  game: "",
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "",
  evolvesInto: "Arbok",
  evolutionMethod: "",
  tip: ""
},
{
  number: 24,
  name: "Arbok",
  type: ["Poison"],
  game: "",
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "Ekans",
  evolvesInto: "",
  evolutionMethod: "",
  tip: ""
},
{
  number: 25,
  name: "Pikachu",
  type: ["Electric"],
  game: "",
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "Pichu",
  evolvesInto: "Raichu",
  evolutionMethod: "",
  tip: ""
},
{
  number: 26,
  name: "Raichu",
  type: ["Electric"],
  game: "",
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "Pikachu",
  evolvesInto: "",
  evolutionMethod: "",
  tip: ""
},
{
  number: 27,
  name: "Sandshrew",
  type: ["Ground"],
  game: "",
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "",
  evolvesInto: "Sandslash",
  evolutionMethod: "",
  tip: ""
},
{
  number: 28,
  name: "Sandslash",
  type: ["Ground"],
  game: "",
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "Sandshrew",
  evolvesInto: "",
  evolutionMethod: "",
  tip: ""
},
{
  number: 29,
  name: "Nidoran♀",
  type: ["Poison"],
  game: "",
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "",
  evolvesInto: "Nidorina",
  evolutionMethod: "",
  tip: ""
},
{
  number: 30,
  name: "Nidorina",
  type: ["Poison"],
  game: "",
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "Nidoran♀",
  evolvesInto: "Nidoqueen",
  evolutionMethod: "",
  tip: ""
}
