const pokemonKanto = [
  {
    number: 1,
    name: "Bulbasaur",
    type: ["Grass", "Poison"],
    game: "",
    dlc: null,
    location: "",
    area: "",
    habitat: "",
    obtainMethod: "",
    requirements: "",
    evolvesFrom: "",
    evolvesInto: "Ivysaur",
    evolutionMethod: "",
    tip: ""
  },
  {
    number: 2,
    name: "Ivysaur",
    type: ["Grass", "Poison"],
    game: "",
    dlc: null,
    location: "",
    area: "",
    habitat: "",
    obtainMethod: "",
    requirements: "",
    evolvesFrom: "Bulbasaur",
    evolvesInto: "Venusaur",
    evolutionMethod: "",
    tip: ""
  },
  {
    number: 3,
    name: "Venusaur",
    type: ["Grass", "Poison"],
    game: "",
    dlc: null,
    location: "",
    area: "",
    habitat: "",
    obtainMethod: "",
    requirements: "",
    evolvesFrom: "Ivysaur",
    evolvesInto: "",
    evolutionMethod: "",
    tip: ""
  },
  {
    number: 4,
    name: "Charmander",
    type: ["Fire"],
    game: "",
    dlc: null,
    location: "",
    area: "",
    habitat: "",
    obtainMethod: "",
    requirements: "",
    evolvesFrom: "",
    evolvesInto: "Charmeleon",
    evolutionMethod: "",
    tip: ""
  },
  {
    number: 5,
    name: "Charmeleon",
    type: ["Fire"],
    game: "",
    dlc: null,
    location: "",
    area: "",
    habitat: "",
    obtainMethod: "",
    requirements: "",
    evolvesFrom: "Charmander",
    evolvesInto: "Charizard",
    evolutionMethod: "",
    tip: ""
  },
  {
    number: 6,
    name: "Charizard",
    type: ["Fire", "Flying"],
    game: "",
    dlc: null,
    location: "",
    area: "",
    habitat: "",
    obtainMethod: "",
    requirements: "",
    evolvesFrom: "Charmeleon",
    evolvesInto: "",
    evolutionMethod: "",
    tip: ""
  },
  {
    number: 7,
    name: "Squirtle",
    type: ["Water"],
    game: "",
    dlc: null,
    location: "",
    area: "",
    habitat: "",
    obtainMethod: "",
    requirements: "",
    evolvesFrom: "",
    evolvesInto: "Wartortle",
    evolutionMethod: "",
    tip: ""
  },
  {
    number: 8,
    name: "Wartortle",
    type: ["Water"],
    game: "",
    dlc: null,
    location: "",
    area: "",
    habitat: "",
    obtainMethod: "",
    requirements: "",
    evolvesFrom: "Squirtle",
    evolvesInto: "Blastoise",
    evolutionMethod: "",
    tip: ""
  },
  {
    number: 9,
    name: "Blastoise",
    type: ["Water"],
    game: "",
    dlc: null,
    location: "",
    area: "",
    habitat: "",
    obtainMethod: "",
    requirements: "",
    evolvesFrom: "Wartortle",
    evolvesInto: "",
    evolutionMethod: "",
    tip: ""
  },
  {
    ,
{
  number: 10,
  name: "Pidgey",
  type: ["Normal", "Flying"],
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "",
  evolvesInto: "Pidgeotto",
  evolutionMethod: "",
  tip: ""
},
{
  number: 11,
  name: "Pidgeotto",
  type: ["Normal", "Flying"],
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "Pidgey",
  evolvesInto: "Pidgeot",
  evolutionMethod: "",
  tip: ""
},
{
  number: 12,
  name: "Pidgeot",
  type: ["Normal", "Flying"],
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "Pidgeotto",
  evolvesInto: "",
  evolutionMethod: "",
  tip: ""
},
{
  number: 13,
  name: "Oddish",
  type: ["Grass", "Poison"],
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "",
  evolvesInto: "Gloom",
  evolutionMethod: "",
  tip: ""
},
{
  number: 14,
  name: "Gloom",
  type: ["Grass", "Poison"],
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "Oddish",
  evolvesInto: "Vileplume / Bellossom",
  evolutionMethod: "",
  tip: ""
},
{
  number: 15,
  name: "Vileplume",
  type: ["Grass", "Poison"],
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "Gloom",
  evolvesInto: "",
  evolutionMethod: "",
  tip: ""
},
{
  number: 16,
  name: "Bellossom",
  type: ["Grass"],
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "Gloom",
  evolvesInto: "",
  evolutionMethod: "",
  tip: ""
},
{
  number: 17,
  name: "Paras",
  type: ["Bug", "Grass"],
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "",
  evolvesInto: "Parasect",
  evolutionMethod: "",
  tip: ""
},
{
  number: 18,
  name: "Parasect",
  type: ["Bug", "Grass"],
  dlc: false,
  location: "",
  area: "",
  habitat: "",
  obtainMethod: "",
  requirements: "",
  evolvesFrom: "Paras",
  evolvesInto: "",
  evolutionMethod: "",
  tip: ""
},
{
  number: 19,
  name: "Venonat",
  type: ["Bug", "Poison"],
  dlc: false,
  evolvesFrom: "",
  evolvesInto: "Venomoth"
},
{
  number: 20,
  name: "Venomoth",
  type: ["Bug", "Poison"],
  dlc: false,
  evolvesFrom: "Venonat",
  evolvesInto: ""
},
{
  number: 21,
  name: "Bellsprout",
  type: ["Grass", "Poison"],
  dlc: false,
  evolvesFrom: "",
  evolvesInto: "Weepinbell"
},
{
  number: 22,
  name: "Weepinbell",
  type: ["Grass", "Poison"],
  dlc: false,
  evolvesFrom: "Bellsprout",
  evolvesInto: "Victreebel"
},
{
  number: 23,
  name: "Victreebel",
  type: ["Grass", "Poison"],
  dlc: false,
  evolvesFrom: "Weepinbell",
  evolvesInto: ""
},
{
  number: 24,
  name: "Slowpoke",
  type: ["Water", "Psychic"],
  dlc: false,
  evolvesFrom: "",
  evolvesInto: "Slowbro / Slowking"
},
{
  number: 25,
  name: "Slowbro",
  type: ["Water", "Psychic"],
  dlc: false,
  evolvesFrom: "Slowpoke",
  evolvesInto: ""
},
{
  number: 26,
  name: "Slowking",
  type: ["Water", "Psychic"],
  dlc: false,
  evolvesFrom: "Slowpoke",
  evolvesInto: ""
},
{
  number: 27,
  name: "Magnemite",
  type: ["Electric", "Steel"],
  dlc: false,
  evolvesFrom: "",
  evolvesInto: "Magneton"
},
{
  number: 28,
  name: "Magneton",
  type: ["Electric", "Steel"],
  dlc: false,
  evolvesFrom: "Magnemite",
  evolvesInto: "Magnezone"
},
{
  number: 29,
  name: "Magnezone",
  type: ["Electric", "Steel"],
  dlc: false,
  evolvesFrom: "Magneton",
  evolvesInto: ""
},
{
  number: 30,
  name: "Onix",
  type: ["Rock", "Ground"],
  dlc: false,
  evolvesFrom: "",
  evolvesInto: "Steelix"
},
{
  number: 31,
  name: "Steelix",
  type: ["Steel", "Ground"],
  dlc: false,
  evolvesFrom: "Onix",
  evolvesInto: ""
},
{
  number: 32,
  name: "Cubone",
  type: ["Ground"],
  dlc: false,
  evolvesFrom: "",
  evolvesInto: "Marowak"
},
{
  number: 33,
  name: "Marowak",
  type: ["Ground"],
  dlc: false,
  evolvesFrom: "Cubone",
  evolvesInto: ""
},
{
  number: 34,
  name: "Tyrogue",
  type: ["Fighting"],
  dlc: false,
  evolvesFrom: "",
  evolvesInto: "Hitmonlee / Hitmonchan / Hitmontop"
},
{
  number: 35,
  name: "Hitmonlee",
  type: ["Fighting"],
  dlc: false,
  evolvesFrom: "Tyrogue",
  evolvesInto: ""
},
{
  number: 36,
  name: "Hitmonchan",
  type: ["Fighting"],
  dlc: false,
  evolvesFrom: "Tyrogue",
  evolvesInto: ""
},
{
  number: 37,
  name: "Hitmontop",
  type: ["Fighting"],
  dlc: false,
  evolvesFrom: "Tyrogue",
  evolvesInto: ""
},
{
  number: 38,
  name: "Koffing",
  type: ["Poison"],
  dlc: false,
  evolvesFrom: "",
  evolvesInto: "Weezing"
},
{
  number: 39,
  name: "Weezing",
  type: ["Poison"],
  dlc: false,
  evolvesFrom: "Koffing",
  evolvesInto: ""
},
{
  number: 40,
  name: "Tangela",
  type: ["Grass"],
  dlc: false,
  evolvesFrom: "",
  evolvesInto: "Tangrowth"
}
];
