// ========================================
// NLPokopia - Pokopia itemdatabase
// Schoongemaakte versie - 288 unieke bevestigde items
// ========================================

const pokopiaItems = {
  "Adventure Kit": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/adventure-kit.png" },
  "Antique chest": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/antique-chest.png" },
  "Antique dresser": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/antique-dresser.png" },
  "Arcanine Doll": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/arcanine-doll.png" },
  "Armor fragment": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/armor-fragment.png" },
  "Avalugg Table": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/avalugg-table.png" },
  "Beach Volleyball Set": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/beach-volleyball-set.png" },
  "Berry case": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/berry-case.png" },
  "Berry chair": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/berry-chair.png" },
  "Berry table": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/berry-table.png" },
  "Big Storage Box": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/big-storage-box.png" },
  "Big Swim Ring": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/big-swim-ring.png" },
  "Big Treasure Chest": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/big-treasure-chest.png" },
  "Black paint": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/black-paint.png" },
  "Blank Canvas": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/blank-canvas.png" },
  "Bonfire": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/bonfire.png" },
  "Book": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/book.png" },
  "Book stack": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/book-stack.png" },
  "Bookcase": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/bookcase.png" },
  "Brick": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/brick.png" },
  "Buried pearl": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/buried-pearl.png" },
  "Cannon": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/cannon.png" },
  "Cart": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/cart.png" },
  "Cash Register": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/cash-register.png" },
  "Cash Register (lit)": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/cash-register-lit.png" },
  "Castform Weather Charm (rain)": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/castform-weather-charm-rain.png" },
  "Castform Weather Charm (Sun)": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/castform-weather-charm-sun.png" },
  "CD Player": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/cd-player.png" },
  "CD Rack": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/cd-rack.png" },
  "Chansey Plant": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/chansey-plant.png" },
  "Chic Chair": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/chic-chair.png" },
  "Chic Sofa": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/chic-sofa.png" },
  "Chic Table": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/chic-table.png" },
  "Chimney Rocks": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/chimney-rocks.png" },
  "Chocolate Cookies": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/chocolate-cookies.png" },
  "Cleaning Supplies": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/cleaning-supplies.png" },
  "Cloud Table": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/cloud-table.png" },
  "Colorful Corals": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/colorful-corals.png" },
  "Computer": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/computer.png" },
  "Concrete": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/concrete.png" },
  "Concrete Pipe": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/concrete-pipe.png" },
  "Construction supplies": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/construction-supplies.png" },
  "Control Unit": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/control-unit.png" },
  "Cooking stove": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/cooking-stove.png" },
  "Cooler": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/cooler.png" },
  "Copper ingot": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/copper-ingot.png" },
  "Copper ore": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/copper-ore.png" },
  "Cotton Spores": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/cotton-spores.png" },
  "Cotton spores (outdoor)": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/cotton-spores-outdoor.png" },
  "Counter": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/counter.png" },
  "Crossing Gate": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/crossing-gate.png" },
  "Crystal fragment": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/crystal-fragment.png" },
  "Cushion bed": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/cushion-bed.png" },
  "Cute Bed": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/cute-bed.png" },
  "Cute Dresser": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/cute-dresser.png" },
  "Cute Lamp": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/cute-lamp.png" },
  "Cute Sofa": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/cute-sofa.png" },
  "Cute Table": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/cute-table.png" },
  "Cutting Board": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/cutting-board.png" },
  "Dandy Flowers": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/dandy-flowers.png" },
  "Decorative Dive Ball": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/decorative-dive-ball.png" },
  "Decorative Great Ball": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/decorative-great-ball.png" },
  "Decorative Heal Ball": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/decorative-heal-ball.png" },
  "Decorative Lure Ball": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/decorative-lure-ball.png" },
  "Decorative Net Ball": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/decorative-net-ball.png" },
  "Decorative plates": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/decorative-plates.png" },
  "Decorative Quick Ball": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/decorative-quick-ball.png" },
  "Decorative shop shelf": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/decorative-shop-shelf.png" },
  "Desk Light": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/desk-light.png" },
  "Dining cabinet": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/dining-cabinet.png" },
  "Dragonite Doll": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/dragonite-doll.png" },
  "Duckweed": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/duckweed.png" },
  "Eerie Candle": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/eerie-candle.png" },
  "Eevee Doll": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/eevee-doll.png" },
  "Excavation tools": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/excavation-tools.png" },
  "Fan": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/fan.png" },
  "Firepit": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/firepit.png" },
  "First Aid Kit": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/first-aid-kit.png" },
  "Fishing Rod": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/fishing-rod.png" },
  "Floating Logs": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/floating-logs.png" },
  "Floor switch": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/floor-switch.png" },
  "Flower Backpack": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/flower-backpack.png" },
  "Flower Cushion": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/flower-cushion.png" },
  "Flowery Table Setting": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/flowery-table-setting.png" },
  "Fluff": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/fluff.png" },
  "Folding Chair": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/folding-chair.png" },
  "Food Counter": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/food-counter.png" },
  "Frying Pan": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/frying-pan.png" },
  "Gaming Bed": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/gaming-bed.png" },
  "Gaming Chair": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/gaming-chair.png" },
  "Gaming Fridge": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/gaming-fridge.png" },
  "Gaming PC": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/gaming-pc.png" },
  "Garbage Bags": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/garbage-bags.png" },
  "Garbage Bin": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/garbage-bin.png" },
  "Garden Chair": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/garden-chair.png" },
  "Garden Light": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/garden-light.png" },
  "Garden Table": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/garden-table.png" },
  "Glass": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/glass.png" },
  "Gold ingot": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/gold-ingot.png" },
  "Gold Teeth": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/gold-teeth.png" },
  "Grass Flooring": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/grass-flooring.png" },
  "Gravestone": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/gravestone.png" },
  "Grubby pearl": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/grubby-pearl.png" },
  "Gyarados Fountain": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/gyarados-fountain.png" },
  "Hanging scroll": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/hanging-scroll.png" },
  "Harp": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/harp.png" },
  "Honey": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/honey.png" },
  "Hoppip Water Bottle": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/hoppip-water-bottle.png" },
  "Hot-Spring Spout": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/hot-spring-spout.png" },
  "Humidifier": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/humidifier.png" },
  "Industrial Bed": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/industrial-bed.png" },
  "Industrial Chair": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/industrial-chair.png" },
  "Industrial Desk": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/industrial-desk.png" },
  "Inflatable Boat": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/inflatable-boat.png" },
  "Iron Bed": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/iron-bed.png" },
  "Iron Chair": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/iron-chair.png" },
  "Iron ingot": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/iron-ingot.png" },
  "Iron ore": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/iron-ore.png" },
  "Iron Pipes": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/iron-pipes.png" },
  "Iron Scaffold": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/iron-scaffold.png" },
  "Iron Table": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/iron-table.png" },
  "Jaw Fossil": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/jaw-fossil.png" },
  "Jirachi Lamp": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/jirachi-lamp.png" },
  "Jumbled Cords": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/jumbled-cords.png" },
  "Kitchen Table": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/kitchen-table.png" },
  "Knitting Supplies": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/knitting-supplies.png" },
  "Lampion": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/lampion.png" },
  "Lantern": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/lantern.png" },
  "Laptop": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/laptop.png" },
  "Large Boulder": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/large-boulder.png" },
  "Large mirror": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/large-mirror.png" },
  "Large Palm Tree": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/large-palm-tree.png" },
  "Letter": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/letter.png" },
  "Log Bed": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/log-bed.png" },
  "Log Chair": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/log-chair.png" },
  "Log table": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/log-table.png" },
  "Lost Relic (large)": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/lost-relic-large.png" },
  "Lunch Box": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/lunch-box.png" },
  "Lumber": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/lumber.png" },
  "Lush Seaweed": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/lush-seaweed.png" },
  "Luxury Bed": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/luxury-bed.png" },
  "Luxury dresser": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/luxury-dresser.png" },
  "Luxury Lamp": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/luxury-lamp.png" },
  "Luxury Sofa": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/luxury-sofa.png" },
  "Luxury table": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/luxury-table.png" },
  "Magazine Rack": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/magazine-rack.png" },
  "Malicious Armor": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/malicious-armor.png" },
  "Map and Compass": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/map-and-compass.png" },
  "Marine Chair": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/marine-chair.png" },
  "Marine Chest": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/marine-chest.png" },
  "Marine Closet": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/marine-closet.png" },
  "Marine dresser": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/marine-dresser.png" },
  "Marine sofa": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/marine-sofa.png" },
  "Menu Board": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/menu-board.png" },
  "Metal Drum": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/metal-drum.png" },
  "Microscope": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/microscope.png" },
  "Microwave Oven": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/microwave-oven.png" },
  "Mini generator": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/mini-generator.png" },
  "Modern sink": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/modern-sink.png" },
  "Molten Rock": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/molten-rock.png" },
  "Moonlight Dance Statue": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/moonlight-dance-statue.png" },
  "Moss": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/moss.png" },
  "Mossy Boulder": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/mossy-boulder.png" },
  "Mossy Stone": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/mossy-stone.png" },
  "Mountain Flowers": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/mountain-flowers.png" },
  "Mug": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/mug.png" },
  "Munna bank": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/munna-bank.png" },
  "Mushroom Lamp": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/mushroom-lamp.png" },
  "Music Box": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/music-box.png" },
  "Naptime bed": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/naptime-bed.png" },
  "Netting": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/netting.png" },
  "Newspaper": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/newspaper.png" },
  "Nonburnable garbage": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/nonburnable-garbage.png" },
  "Office cabinet": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/office-cabinet.png" },
  "Office Chair": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/office-chair.png" },
  "Office Desk": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/office-desk.png" },
  "Office locker": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/office-locker.png" },
  "Office Shelf": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/office-shelf.png" },
  "Office table": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/office-table.png" },
  "Open Book": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/open-book.png" },
  "Ornate bed": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/ornate-bed.png" },
  "Ornate Partition": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/ornate-partition.png" },
  "Ornate Stand": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/ornate-stand.png" },
  "Paper": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/paper.png" },
  "Paper Party Cups": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/paper-party-cups.png" },
  "Papers": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/papers.png" },
  "Party Platter": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/party-platter.png" },
  "Pencil Holder": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/pencil-holder.png" },
  "Perch": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/perch.png" },
  "Photo Cutout Board": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/photo-cutout-board.png" },
  "Photo Frame": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/photo-frame.png" },
  "Pichu Doll": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/pichu-doll.png" },
  "Pickaxe": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/pickaxe.png" },
  "Picnic Basket": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/picnic-basket.png" },
  "Pikachu Doll": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/pikachu-doll.png" },
  "Pikachu Sofa": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/pikachu-sofa.png" },
  "Pitcher-plant pot": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/pitcher-plant-pot.png" },
  "Pizza": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/pizza.png" },
  "Plain Bed": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/plain-bed.png" },
  "Plain chest": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/plain-chest.png" },
  "Plain closet": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/plain-closet.png" },
  "Plain Lamp": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/plain-lamp.png" },
  "Plain sofa": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/plain-sofa.png" },
  "Plain Table": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/plain-table.png" },
  "Plated Food": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/plated-food.png" },
  "Pointy Tree": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/pointy-tree.png" },
  "Poké Ball Bed": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/poke-ball-bed.png" },
  "Poké Ball Chest": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/poke-ball-chest.png" },
  "Poké Ball Light": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/poke-ball-light.png" },
  "Poké Ball Sofa": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/poke-ball-sofa.png" },
  "Poké Ball table": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/poke-ball-table.png" },
  "Pokémetal": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/pokemetal.png" },
  "Pop Art Bed": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/pop-art-bed.png" },
  "Pop Art Sofa": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/pop-art-sofa.png" },
  "Pop art table": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/pop-art-table.png" },
  "Public seat": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/public-seat.png" },
  "Puffy-tree pillar": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/puffy-tree-pillar.png" },
  "Punching Bag": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/punching-bag.png" },
  "Punching Game": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/punching-game.png" },
  "Push Cart": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/push-cart.png" },
  "Raichu Sign": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/raichu-sign.png" },
  "Railway Track": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/railway-track.png" },
  "Rare Pokémetal": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/rare-pokemetal.png" },
  "Red crystal fragment": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/red-crystal-fragment.png" },
  "Resort Hammock": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/resort-hammock.png" },
  "Resort Light": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/resort-light.png" },
  "Resort sofa": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/resort-sofa.png" },
  "Resort Table": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/resort-table.png" },
  "Ribbon Cake": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/ribbon-cake.png" },
  "Rope": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/rope.png" },
  "Sail Fossil": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/sail-fossil.png" },
  "Sand Bed": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/sand-bed.png" },
  "Sand Toys": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/sand-toys.png" },
  "Sandbags": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/sandbags.png" },
  "Sandpile": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/sandpile.png" },
  "Sandwiches": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/sandwiches.png" },
  "Science Experiment": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/science-experiment.png" },
  "Sea glass fragments": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/sea-glass-fragments.png" },
  "Sea Moss": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/sea-moss.png" },
  "Seabed Flowers": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/seabed-flowers.png" },
  "Seashell": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/seashell.png" },
  "Seashell Seat": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/seashell-seat.png" },
  "Seashore Flowers": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/seashore-flowers.png" },
  "Servers": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/servers.png" },
  "Sewer-hole Cover": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/sewer-hole-cover.png" },
  "Shaved Ice": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/shaved-ice.png" },
  "Shell Lamp (lit)": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/shell-lamp-lit.png" },
  "Shiny pearl": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/shiny-pearl.png" },
  "Shower": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/shower.png" },
  "Side Table": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/side-table.png" },
  "Sign": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/sign.png" },
  "Simple Cushion": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/simple-cushion.png" },
  "Sink": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/sink.png" },
  "Skull Fossil": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/skull-fossil.png" },
  "Skyland Flowers": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/skyland-flowers.png" },
  "Slide": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/slide.png" },
  "Slender Candle": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/slender-candle.png" },
  "Small Coral": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/small-coral.png" },
  "Small Stage": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/small-stage.png" },
  "Small Stage (lit)": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/small-stage-lit.png" },
  "Small Vase": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/small-vase.png" },
  "Smelting Furnace": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/smelting-furnace.png" },
  "Soda Float": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/soda-float.png" },
  "Sparkling Jewelry": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/sparkling-jewelry.png" },
  "Speaker": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/speaker.png" },
  "Spotlight": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/spotlight.png" },
  "Stalagmites": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/stalagmites.png" },
  "Standing Mic": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/standing-mic.png" },
  "Star Closet": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/star-closet.png" },
  "Starry-sky Bed": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/starry-sky-bed.png" },
  "Step Stool": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/step-stool.png" },
  "Stepping Stones": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/stepping-stones.png" },
  "Stone": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/stone.png" },
  "Stone bench": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/stone-bench.png" },
  "Stone fireplace": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/stone-fireplace.png" },
  "Stone table": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/stone-table.png" },
  "Stone tiling": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/stone-tiling.png" },
  "Storage Box": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/storage-box.png" },
  "Strange strings": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/strange-strings.png" },
  "Straw Bed": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/straw-bed.png" },
  "Straw stool": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/straw-stool.png" },
  "Straw Table": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/straw-table.png" },
  "Striped wall": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/striped-wall.png" },
  "Strength Rock": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/strength-rock.png" },
  "Sturdy stick": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/sturdy-stick.png" },
  "Stylish Cooking Pot": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/stylish-cooking-pot.png" },
  "Stylish stool": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/stylish-stool.png" },
  "Stylish tiling": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/stylish-tiling.png" },
  "Squishy clay": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/squishy-clay.png" },
  "Swim Ring": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/swim-ring.png" },
  "Tabletop Mic": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/tabletop-mic.png" },
  "Tablet": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/tablet.png" },
  "Tall Coral": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/tall-coral.png" },
  "Team Rocket Wall Hanging": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/team-rocket-wall-hanging.png" },
  "Television": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/television.png" },
  "Tinkagear": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/tinkagear.png" },
  "Tire Toy": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/tire-toy.png" },
  "Tires": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/tires.png" },
  "Toolbox": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/toolbox.png" },
  "Torch": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/torch.png" },
  "Towel Rack": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/towel-rack.png" },
  "Traffic Cone": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/traffic-cone.png" },
  "Treasure": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/treasure.png" },
  "Twine": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/twine.png" },
  "Utility Pole": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/utility-pole.png" },
  "Vending Machine": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/vending-machine.png" },
  "Vine wall decoration": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/vine-wall-decoration.png" },
  "Walkway": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/walkway.png" },
  "Wall clock": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wall-clock.png" },
  "Wall mirror": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wall-mirror.png" },
  "Wall plant": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wall-plant.png" },
  "Wall storage box": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wall-storage-box.png" },
  "Wall torch": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wall-torch.png" },
  "Wall-mounted table": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wall-mounted-table.png" },
  "Wastepaper": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wastepaper.png" },
  "Water pillar quarter": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/water-pillar-quarter.png" },
  "Watermelon": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/watermelon.png" },
  "Weather vane": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/weather-vane.png" },
  "Wheelbarrow": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wheelbarrow.png" },
  "Whiteboard": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/whiteboard.png" },
  "Wiggly mirror": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wiggly-mirror.png" },
  "Windup Inkay": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/windup-inkay.png" },
  "Wireless power transmitter": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wireless-power-transmitter.png" },
  "Wireless Power-Transmitter Post (lit)": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wireless-power-transmitter-post-lit.png" },
  "Wireless power-transmitter switch": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wireless-power-transmitter-switch.png" },
  "Wood partition": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wood-partition.png" },
  "Wooden Birdhouse": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wooden-birdhouse.png" },
  "Wooden Crate": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wooden-crate.png" },
  "Wooden Path": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wooden-path.png" },
  "Wooden plate": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wooden-plate.png" },
  "Wooden posts": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wooden-posts.png" },
  "Wooden table": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wooden-table.png" },
  "Worn treasure chest": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/worn-treasure-chest.png" },
  "Wreath": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wreath.png" },
  "Wing fossil (body)": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wing-fossil-body.png" },
  "Wing Fossil (head)": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wing-fossil-head.png" },
  "Wing Fossil (left wing)": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wing-fossil-left-wing.png" },
  "Wing Fossil (right wing)": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wing-fossil-right-wing.png" },
  "Wing Fossil (tail)": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/wing-fossil-tail.png" },
  "Cardboard Boxes": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/cardboard-boxes.png" },
  "Waste Bin (any)": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/garbage-bin.png" },
  "Sign (any)": { image: "https://pokesprite.tootaio.com/extras/pokopia-items/sign.png" }
};

function normalizePokopiaItemName(itemName) {
  return String(itemName || "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .trim()
    .toLowerCase();
}

const pokopiaItemsByNormalizedName = Object.fromEntries(
  Object.entries(pokopiaItems).map(([name, data]) => [
    normalizePokopiaItemName(name),
    data
  ])
);

function getPokopiaItem(itemName) {
  if (!itemName) return null;

  return (
    pokopiaItems[itemName] ||
    pokopiaItemsByNormalizedName[normalizePokopiaItemName(itemName)] ||
    null
  );
}

function getPokopiaItemImage(itemName) {
  return getPokopiaItem(itemName)?.image || null;
}

window.pokopiaItems = pokopiaItems;
window.getPokopiaItem = getPokopiaItem;
window.getPokopiaItemImage = getPokopiaItemImage;
