// ========================================
// NLPokopia - Pokopia itemdatabase
// Schoongemaakte versie - 288 unieke bevestigde items
// ========================================

const pokopiaItems = {
  "Adventure Kit": { image: "images/items/adventure-kit.png" },
  "Antique chest": { image: "images/items/antique-chest.png" },
  "Antique dresser": { image: "images/items/antique-dresser.png" },
  "Arcanine Doll": { image: "images/items/arcanine-doll.png" },
  "Armor fragment": { image: "images/items/armor-fragment.png" },
  "Avalugg Table": { image: "images/items/avalugg-table.png" },
  "Beach Volleyball Set": { image: "images/items/beach-volleyball-set.png" },
  "Berry case": { image: "images/items/berry-case.png" },
  "Berry chair": { image: "images/items/berry-chair.png" },
  "Berry table": { image: "images/items/berry-table.png" },
  "Big Storage Box": { image: "images/items/big-storage-box.png" },
  "Big Swim Ring": { image: "images/items/big-swim-ring.png" },
  "Big Treasure Chest": { image: "images/items/big-treasure-chest.png" },
  "Black paint": { image: "images/items/black-paint.png" },
  "Blank Canvas": { image: "images/items/blank-canvas.png" },
  "Bonfire": { image: "images/items/bonfire.png" },
  "Book": { image: "images/items/book.png" },
  "Book stack": { image: "images/items/book-stack.png" },
  "Bookcase": { image: "images/items/bookcase.png" },
  "Brick": { image: "images/items/brick.png" },
  "Buried pearl": { image: "images/items/buried-pearl.png" },
  "Cannon": { image: "images/items/cannon.png" },
  "Cart": { image: "images/items/cart.png" },
  "Cash Register": { image: "images/items/cash-register.png" },
  "Cash Register (lit)": { image: "images/items/cash-register-lit.png" },
  "Castform Weather Charm (rain)": { image: "images/items/castform-weather-charm-rain.png" },
  "Castform Weather Charm (Sun)": { image: "images/items/castform-weather-charm-sun.png" },
  "CD Player": { image: "images/items/cd-player.png" },
  "CD Rack": { image: "images/items/cd-rack.png" },
  "Chansey Plant": { image: "images/items/chansey-plant.png" },
  "Chic Chair": { image: "images/items/chic-chair.png" },
  "Chic Sofa": { image: "images/items/chic-sofa.png" },
  "Chic Table": { image: "images/items/chic-table.png" },
  "Chimney Rocks": { image: "images/items/chimney-rocks.png" },
  "Chocolate Cookies": { image: "images/items/chocolate-cookies.png" },
  "Cleaning Supplies": { image: "images/items/cleaning-supplies.png" },
  "Cloud Table": { image: "images/items/cloud-table.png" },
  "Colorful Corals": { image: "images/items/colorful-corals.png" },
  "Computer": { image: "images/items/computer.png" },
  "Concrete": { image: "images/items/concrete.png" },
  "Concrete Pipe": { image: "images/items/concrete-pipe.png" },
  "Construction supplies": { image: "images/items/construction-supplies.png" },
  "Control Unit": { image: "images/items/control-unit.png" },
  "Cooking stove": { image: "images/items/cooking-stove.png" },
  "Cooler": { image: "images/items/cooler.png" },
  "Copper ingot": { image: "images/items/copper-ingot.png" },
  "Copper ore": { image: "images/items/copper-ore.png" },
  "Cotton Spores": { image: "images/items/cotton-spores.png" },
  "Cotton spores (outdoor)": { image: "images/items/cotton-spores-outdoor.png" },
  "Counter": { image: "images/items/counter.png" },
  "Crossing Gate": { image: "images/items/crossing-gate.png" },
  "Crystal fragment": { image: "images/items/crystal-fragment.png" },
  "Cushion bed": { image: "images/items/cushion-bed.png" },
  "Cute Bed": { image: "images/items/cute-bed.png" },
  "Cute Dresser": { image: "images/items/cute-dresser.png" },
  "Cute Lamp": { image: "images/items/cute-lamp.png" },
  "Cute Sofa": { image: "images/items/cute-sofa.png" },
  "Cute Table": { image: "images/items/cute-table.png" },
  "Cutting Board": { image: "images/items/cutting-board.png" },
  "Dandy Flowers": { image: "images/items/dandy-flowers.png" },
  "Decorative Dive Ball": { image: "images/items/decorative-dive-ball.png" },
  "Decorative Great Ball": { image: "images/items/decorative-great-ball.png" },
  "Decorative Heal Ball": { image: "images/items/decorative-heal-ball.png" },
  "Decorative Lure Ball": { image: "images/items/decorative-lure-ball.png" },
  "Decorative Net Ball": { image: "images/items/decorative-net-ball.png" },
  "Decorative plates": { image: "images/items/decorative-plates.png" },
  "Decorative Quick Ball": { image: "images/items/decorative-quick-ball.png" },
  "Decorative shop shelf": { image: "images/items/decorative-shop-shelf.png" },
  "Desk Light": { image: "images/items/desk-light.png" },
  "Dining cabinet": { image: "images/items/dining-cabinet.png" },
  "Dragonite Doll": { image: "images/items/dragonite-doll.png" },
  "Duckweed": { image: "images/items/duckweed.png" },
  "Eerie Candle": { image: "images/items/eerie-candle.png" },
  "Eevee Doll": { image: "images/items/eevee-doll.png" },
  "Excavation tools": { image: "images/items/excavation-tools.png" },
  "Fan": { image: "images/items/fan.png" },
  "Firepit": { image: "images/items/firepit.png" },
  "First Aid Kit": { image: "images/items/first-aid-kit.png" },
  "Fishing Rod": { image: "images/items/fishing-rod.png" },
  "Floating Logs": { image: "images/items/floating-logs.png" },
  "Floor switch": { image: "images/items/floor-switch.png" },
  "Flower Backpack": { image: "images/items/flower-backpack.png" },
  "Flower Cushion": { image: "images/items/flower-cushion.png" },
  "Flowery Table Setting": { image: "images/items/flowery-table-setting.png" },
  "Fluff": { image: "images/items/fluff.png" },
  "Folding Chair": { image: "images/items/folding-chair.png" },
  "Food Counter": { image: "images/items/food-counter.png" },
  "Frying Pan": { image: "images/items/frying-pan.png" },
  "Gaming Bed": { image: "images/items/gaming-bed.png" },
  "Gaming Chair": { image: "images/items/gaming-chair.png" },
  "Gaming Fridge": { image: "images/items/gaming-fridge.png" },
  "Gaming PC": { image: "images/items/gaming-pc.png" },
  "Garbage Bags": { image: "images/items/garbage-bags.png" },
  "Garbage Bin": { image: "images/items/garbage-bin.png" },
  "Garden Chair": { image: "images/items/garden-chair.png" },
  "Garden Light": { image: "images/items/garden-light.png" },
  "Garden Table": { image: "images/items/garden-table.png" },
  "Glass": { image: "images/items/glass.png" },
  "Gold ingot": { image: "images/items/gold-ingot.png" },
  "Gold Teeth": { image: "images/items/gold-teeth.png" },
  "Grass Flooring": { image: "images/items/grass-flooring.png" },
  "Gravestone": { image: "images/items/gravestone.png" },
  "Grubby pearl": { image: "images/items/grubby-pearl.png" },
  "Gyarados Fountain": { image: "images/items/gyarados-fountain.png" },
  "Hanging scroll": { image: "images/items/hanging-scroll.png" },
  "Harp": { image: "images/items/harp.png" },
  "Honey": { image: "images/items/honey.png" },
  "Hoppip Water Bottle": { image: "images/items/hoppip-water-bottle.png" },
  "Hot-Spring Spout": { image: "images/items/hot-spring-spout.png" },
  "Humidifier": { image: "images/items/humidifier.png" },
  "Industrial Bed": { image: "images/items/industrial-bed.png" },
  "Industrial Chair": { image: "images/items/industrial-chair.png" },
  "Industrial Desk": { image: "images/items/industrial-desk.png" },
  "Inflatable Boat": { image: "images/items/inflatable-boat.png" },
  "Iron Bed": { image: "images/items/iron-bed.png" },
  "Iron Chair": { image: "images/items/iron-chair.png" },
  "Iron ingot": { image: "images/items/iron-ingot.png" },
  "Iron ore": { image: "images/items/iron-ore.png" },
  "Iron Pipes": { image: "images/items/iron-pipes.png" },
  "Iron Scaffold": { image: "images/items/iron-scaffold.png" },
  "Iron Table": { image: "images/items/iron-table.png" },
  "Jaw Fossil": { image: "images/items/jaw-fossil.png" },
  "Jirachi Lamp": { image: "images/items/jirachi-lamp.png" },
  "Jumbled Cords": { image: "images/items/jumbled-cords.png" },
  "Kitchen Table": { image: "images/items/kitchen-table.png" },
  "Knitting Supplies": { image: "images/items/knitting-supplies.png" },
  "Lampion": { image: "images/items/lampion.png" },
  "Lantern": { image: "images/items/lantern.png" },
  "Laptop": { image: "images/items/laptop.png" },
  "Large Boulder": { image: "images/items/large-boulder.png" },
  "Large mirror": { image: "images/items/large-mirror.png" },
  "Large Palm Tree": { image: "images/items/large-palm-tree.png" },
  "Letter": { image: "images/items/letter.png" },
  "Log Bed": { image: "images/items/log-bed.png" },
  "Log Chair": { image: "images/items/log-chair.png" },
  "Log table": { image: "images/items/log-table.png" },
  "Lost Relic (large)": { image: "images/items/lost-relic-large.png" },
  "Lunch Box": { image: "images/items/lunch-box.png" },
  "Lumber": { image: "images/items/lumber.png" },
  "Lush Seaweed": { image: "images/items/lush-seaweed.png" },
"Luxury Bed": { image: 
  "https://pokesprite.tootaio.com/extras/pokopia-items/luxury-bed.png" },
  "Luxury dresser": { image: "images/items/luxury-dresser.png" },
  "Luxury Lamp": { image: "images/items/luxury-lamp.png" },
  "Luxury Sofa": { image: "images/items/luxury-sofa.png" },
  "Luxury table": { image: "images/items/luxury-table.png" },
  "Magazine Rack": { image: "images/items/magazine-rack.png" },
  "Malicious Armor": { image: "images/items/malicious-armor.png" },
  "Map and Compass": { image: "images/items/map-and-compass.png" },
  "Marine Chair": { image: "images/items/marine-chair.png" },
  "Marine Chest": { image: "images/items/marine-chest.png" },
  "Marine Closet": { image: "images/items/marine-closet.png" },
  "Marine dresser": { image: "images/items/marine-dresser.png" },
  "Marine sofa": { image: "images/items/marine-sofa.png" },
  "Menu Board": { image: "images/items/menu-board.png" },
  "Metal Drum": { image: "images/items/metal-drum.png" },
  "Microscope": { image: "images/items/microscope.png" },
  "Microwave Oven": { image: "images/items/microwave-oven.png" },
  "Mini generator": { image: "images/items/mini-generator.png" },
  "Modern sink": { image: "images/items/modern-sink.png" },
  "Molten Rock": { image: "images/items/molten-rock.png" },
  "Moonlight Dance Statue": { image: "images/items/moonlight-dance-statue.png" },
  "Moss": { image: "images/items/moss.png" },
  "Mossy Boulder": { image: "images/items/mossy-boulder.png" },
  "Mossy Stone": { image: "images/items/mossy-stone.png" },
  "Mountain Flowers": { image: "images/items/mountain-flowers.png" },
  "Mug": { image: "images/items/mug.png" },
  "Munna bank": { image: "images/items/munna-bank.png" },
  "Mushroom Lamp": { image: "images/items/mushroom-lamp.png" },
  "Music Box": { image: "images/items/music-box.png" },
  "Naptime bed": { image: "images/items/naptime-bed.png" },
  "Netting": { image: "images/items/netting.png" },
  "Newspaper": { image: "images/items/newspaper.png" },
  "Nonburnable garbage": { image: "images/items/nonburnable-garbage.png" },
  "Office cabinet": { image: "images/items/office-cabinet.png" },
  "Office Chair": { image: "images/items/office-chair.png" },
  "Office Desk": { image: "images/items/office-desk.png" },
  "Office locker": { image: "images/items/office-locker.png" },
  "Office Shelf": { image: "images/items/office-shelf.png" },
  "Office table": { image: "images/items/office-table.png" },
  "Open Book": { image: "images/items/open-book.png" },
  "Ornate bed": { image: "images/items/ornate-bed.png" },
  "Ornate Partition": { image: "images/items/ornate-partition.png" },
  "Ornate Stand": { image: "images/items/ornate-stand.png" },
  "Paper": { image: "images/items/paper.png" },
  "Paper Party Cups": { image: "images/items/paper-party-cups.png" },
  "Papers": { image: "images/items/papers.png" },
  "Party Platter": { image: "images/items/party-platter.png" },
  "Pencil Holder": { image: "images/items/pencil-holder.png" },
  "Perch": { image: "images/items/perch.png" },
  "Photo Cutout Board": { image: "images/items/photo-cutout-board.png" },
  "Photo Frame": { image: "images/items/photo-frame.png" },
  "Pichu Doll": { image: "images/items/pichu-doll.png" },
  "Pickaxe": { image: "images/items/pickaxe.png" },
  "Picnic Basket": { image: "images/items/picnic-basket.png" },
  "Pikachu Doll": { image: "images/items/pikachu-doll.png" },
  "Pikachu Sofa": { image: "images/items/pikachu-sofa.png" },
  "Pitcher-plant pot": { image: "images/items/pitcher-plant-pot.png" },
  "Pizza": { image: "images/items/pizza.png" },
  "Plain Bed": { image: "images/items/plain-bed.png" },
  "Plain chest": { image: "images/items/plain-chest.png" },
  "Plain closet": { image: "images/items/plain-closet.png" },
  "Plain Lamp": { image: "images/items/plain-lamp.png" },
  "Plain sofa": { image: "images/items/plain-sofa.png" },
  "Plain Table": { image: "images/items/plain-table.png" },
  "Plated Food": { image: "images/items/plated-food.png" },
  "Pointy Tree": { image: "images/items/pointy-tree.png" },
  "Poké Ball Bed": { image: "images/items/poke-ball-bed.png" },
  "Poké Ball Chest": { image: "images/items/poke-ball-chest.png" },
  "Poké Ball Light": { image: "images/items/poke-ball-light.png" },
  "Poké Ball Sofa": { image: "images/items/poke-ball-sofa.png" },
  "Poké Ball table": { image: "images/items/poke-ball-table.png" },
  "Pokémetal": { image: "images/items/pokemetal.png" },
  "Pop Art Bed": { image: "images/items/pop-art-bed.png" },
  "Pop Art Sofa": { image: "images/items/pop-art-sofa.png" },
  "Pop art table": { image: "images/items/pop-art-table.png" },
  "Public seat": { image: "images/items/public-seat.png" },
  "Puffy-tree pillar": { image: "images/items/puffy-tree-pillar.png" },
  "Punching Bag": { image: "images/items/punching-bag.png" },
  "Punching Game": { image: "images/items/punching-game.png" },
  "Push Cart": { image: "images/items/push-cart.png" },
  "Raichu Sign": { image: "images/items/raichu-sign.png" },
  "Railway Track": { image: "images/items/railway-track.png" },
  "Rare Pokémetal": { image: "images/items/rare-pokemetal.png" },
  "Red crystal fragment": { image: "images/items/red-crystal-fragment.png" },
  "Resort Hammock": { image: "images/items/resort-hammock.png" },
  "Resort Light": { image: "images/items/resort-light.png" },
  "Resort sofa": { image: "images/items/resort-sofa.png" },
  "Resort Table": { image: "images/items/resort-table.png" },
  "Ribbon Cake": { image: "images/items/ribbon-cake.png" },
  "Rope": { image: "images/items/rope.png" },
  "Sail Fossil": { image: "images/items/sail-fossil.png" },
  "Sand Bed": { image: "images/items/sand-bed.png" },
  "Sand Toys": { image: "images/items/sand-toys.png" },
  "Sandbags": { image: "images/items/sandbags.png" },
  "Sandpile": { image: "images/items/sandpile.png" },
  "Sandwiches": { image: "images/items/sandwiches.png" },
  "Science Experiment": { image: "images/items/science-experiment.png" },
  "Sea glass fragments": { image: "images/items/sea-glass-fragments.png" },
  "Sea Moss": { image: "images/items/sea-moss.png" },
  "Seabed Flowers": { image: "images/items/seabed-flowers.png" },
  "Seashell": { image: "images/items/seashell.png" },
  "Seashell Seat": { image: "images/items/seashell-seat.png" },
  "Seashore Flowers": { image: "images/items/seashore-flowers.png" },
  "Servers": { image: "images/items/servers.png" },
  "Sewer-hole Cover": { image: "images/items/sewer-hole-cover.png" },
  "Shaved Ice": { image: "images/items/shaved-ice.png" },
  "Shell Lamp (lit)": { image: "images/items/shell-lamp-lit.png" },
  "Shiny pearl": { image: "images/items/shiny-pearl.png" },
  "Shower": { image: "images/items/shower.png" },
  "Side Table": { image: "images/items/side-table.png" },
  "Sign": { image: "images/items/sign.png" },
  "Simple Cushion": { image: "images/items/simple-cushion.png" },
  "Sink": { image: "images/items/sink.png" },
  "Skull Fossil": { image: "images/items/skull-fossil.png" },
  "Skyland Flowers": { image: "images/items/skyland-flowers.png" },
  "Slide": { image: "images/items/slide.png" },
  "Slender Candle": { image: "images/items/slender-candle.png" },
  "Small Coral": { image: "images/items/small-coral.png" },
  "Small Stage": { image: "images/items/small-stage.png" },
  "Small Stage (lit)": { image: "images/items/small-stage-lit.png" },
  "Small Vase": { image: "images/items/small-vase.png" },
  "Smelting Furnace": { image: "images/items/smelting-furnace.png" },
  "Soda Float": { image: "images/items/soda-float.png" },
  "Sparkling Jewelry": { image: "images/items/sparkling-jewelry.png" },
  "Speaker": { image: "images/items/speaker.png" },
  "Spotlight": { image: "images/items/spotlight.png" },
  "Stalagmites": { image: "images/items/stalagmites.png" },
  "Standing Mic": { image: "images/items/standing-mic.png" },
  "Star Closet": { image: "images/items/star-closet.png" },
  "Starry-sky Bed": { image: "images/items/starry-sky-bed.png" },
  "Step Stool": { image: "images/items/step-stool.png" },
  "Stepping Stones": { image: "images/items/stepping-stones.png" },
  "Stone": { image: "images/items/stone.png" },
  "Stone bench": { image: "images/items/stone-bench.png" },
  "Stone fireplace": { image: "images/items/stone-fireplace.png" },
  "Stone table": { image: "images/items/stone-table.png" },
  "Stone tiling": { image: "images/items/stone-tiling.png" },
  "Storage Box": { image: "images/items/storage-box.png" },
  "Strange strings": { image: "images/items/strange-strings.png" },
  "Straw Bed": { image: "images/items/straw-bed.png" },
  "Straw stool": { image: "images/items/straw-stool.png" },
  "Straw Table": { image: "images/items/straw-table.png" },
  "Striped wall": { image: "images/items/striped-wall.png" },
  "Strength Rock": { image: "images/items/strength-rock.png" },
  "Sturdy stick": { image: "images/items/sturdy-stick.png" },
  "Stylish Cooking Pot": { image: "images/items/stylish-cooking-pot.png" },
  "Stylish stool": { image: "images/items/stylish-stool.png" },
  "Stylish tiling": { image: "images/items/stylish-tiling.png" },
  "Squishy clay": { image: "images/items/squishy-clay.png" },
  "Swim Ring": { image: "images/items/swim-ring.png" },
  "Tabletop Mic": { image: "images/items/tabletop-mic.png" },
  "Tablet": { image: "images/items/tablet.png" },
  "Tall Coral": { image: "images/items/tall-coral.png" },
  "Team Rocket Wall Hanging": { image: "images/items/team-rocket-wall-hanging.png" },
  "Television": { image: "images/items/television.png" },
  "Tinkagear": { image: "images/items/tinkagear.png" },
  "Tire Toy": { image: "images/items/tire-toy.png" },
  "Tires": { image: "images/items/tires.png" },
  "Toolbox": { image: "images/items/toolbox.png" },
  "Torch": { image: "images/items/torch.png" },
  "Towel Rack": { image: "images/items/towel-rack.png" },
  "Traffic Cone": { image: "images/items/traffic-cone.png" },
  "Treasure": { image: "images/items/treasure.png" },
  "Twine": { image: "images/items/twine.png" },
  "Utility Pole": { image: "images/items/utility-pole.png" },
  "Vending Machine": { image: "images/items/vending-machine.png" },
  "Vine wall decoration": { image: "images/items/vine-wall-decoration.png" },
  "Walkway": { image: "images/items/walkway.png" },
  "Wall clock": { image: "images/items/wall-clock.png" },
  "Wall mirror": { image: "images/items/wall-mirror.png" },
  "Wall plant": { image: "images/items/wall-plant.png" },
  "Wall storage box": { image: "images/items/wall-storage-box.png" },
  "Wall torch": { image: "images/items/wall-torch.png" },
  "Wall-mounted table": { image: "images/items/wall-mounted-table.png" },
  "Wastepaper": { image: "images/items/wastepaper.png" },
  "Water pillar quarter": { image: "images/items/water-pillar-quarter.png" },
  "Watermelon": { image: "images/items/watermelon.png" },
  "Weather vane": { image: "images/items/weather-vane.png" },
  "Wheelbarrow": { image: "images/items/wheelbarrow.png" },
  "Whiteboard": { image: "images/items/whiteboard.png" },
  "Wiggly mirror": { image: "images/items/wiggly-mirror.png" },
  "Windup Inkay": { image: "images/items/windup-inkay.png" },
  "Wireless power transmitter": { image: "images/items/wireless-power-transmitter.png" },
  "Wireless Power-Transmitter Post (lit)": { image: "images/items/wireless-power-transmitter-post-lit.png" },
  "Wireless power-transmitter switch": { image: "images/items/wireless-power-transmitter-switch.png" },
  "Wood partition": { image: "images/items/wood-partition.png" },
  "Wooden Birdhouse": { image: "images/items/wooden-birdhouse.png" },
  "Wooden Crate": { image: "images/items/wooden-crate.png" },
  "Wooden Path": { image: "images/items/wooden-path.png" },
  "Wooden plate": { image: "images/items/wooden-plate.png" },
  "Wooden posts": { image: "images/items/wooden-posts.png" },
  "Wooden table": { image: "images/items/wooden-table.png" },
  "Worn treasure chest": { image: "images/items/worn-treasure-chest.png" },
  "Wreath": { image: "images/items/wreath.png" },
  "Wing fossil (body)": { image: "images/items/wing-fossil-body.png" },
  "Wing Fossil (head)": { image: "images/items/wing-fossil-head.png" },
  "Wing Fossil (left wing)": { image: "images/items/wing-fossil-left-wing.png" },
  "Wing Fossil (right wing)": { image: "images/items/wing-fossil-right-wing.png" },
  "Wing Fossil (tail)": { image: "images/items/wing-fossil-tail.png" }
};

function getPokopiaItem(itemName) {
  return pokopiaItems[itemName] || null;
}

function getPokopiaItemImage(itemName) {
  return pokopiaItems[itemName]?.image || null;
}

window.pokopiaItems = pokopiaItems;
window.getPokopiaItem = getPokopiaItem;
window.getPokopiaItemImage = getPokopiaItemImage;
